before_script:
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - bundle install
  - mkdir -p test_output

stages:
  - test

job:
  stage: test
  script:
    - cp Example/Podfile .
    - pod install --project-directory=Example
    - bundle exec fastlane ci_test
    - bash <(curl -s https://codecov.io/bash) -t a9624e7b-9060-4d9b-ab62-c69317883dc7
  artifacts:
    reports:
      junit: test_output/*.xml